# Generated by Django 4.1.5 on 2023-01-30 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "name",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("phn", models.CharField(max_length=200)),
                ("addr", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("prod_name", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="orderhist",
            fields=[
                ("order_no", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "cust",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FIRSTAPPLICATION.customer",
                    ),
                ),
                (
                    "prod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FIRSTAPPLICATION.product",
                    ),
                ),
            ],
        ),
    ]
